FROM golang:1.16-alpine as builder

RUN apk update \
    && apk add --no-cache make gcc musl-dev linux-headers git

ADD ./go-ethereum /src/go-ethereum
RUN cd /src/go-ethereum \
    && make clean all

FROM alpine:latest

COPY --from=builder /src/go-ethereum/build/bin/geth /usr/local/bin
COPY --from=builder /src/go-ethereum/build/bin/bootnode /usr/local/bin

RUN ln -s /usr/local/bin/bootnode /node

EXPOSE 8545 8546 30303 30303/udp
ENTRYPOINT ["/node"]